### ISSUE TITLE
Async callbacks are problematic when receiving ordered messages

### ISSUE THREAD

**Issue by queezle42** [dustin/mqtt-hs#14]
I have run into the problem where received messages are sometimes handled out of order, due to the fact that all callbacks are invoked asynchronous (similar to https://github.com/dustin/mqtt-hs/issues/12, but in my code).

While asynchronous callbacks might be correct for some use cases, they will randomly break every use case that relies on ordered messages. They are also problematic when messages arrive at a rate that is higher than what can be processed by user code.

I think the library user should be responsible for forking during the callback when it is required. Alternatively `MessageCallback` could be extended to have async- and synchronous variants.

And also thank you very much for writing this library!

**Comment by dustin** [comment]
That's reasonable.  I think it used to matter a lot more in a previous design.  I'm certain I rely on this behavior in a few apps, but if I can push that behavior into my app, it might not be too bad.  The remaining tricky part is having callbacks not wreck the whole system.

**Comment by kamek-pf** [comment]
I also observed this behavior in some parts of our code base where ordering is required.
I haven't found another Haskell MQTT client, so I think there's no good solution to this problem currently.

**Comment by dustin** [comment]
Thanks for the input.  I don't currently have any cases where ordering is
required, but it makes sense.  I don't know how deep the assumptions are
anymore, but it should be possible to enforce some ordering.

**Comment by kamek-pf** [comment]
I have a possible implementation for this in #25.

**Comment by dustin** [comment]
I've added a bit of testing for this in my mqttd and also added support for my mqtt-bridge project.  Running a large bridge with ordered messages greatly reduces throughput, but  it's pretty clear.

(of course, it supports both ordered and unordered sources so you can have both high throughput and enforced ordering where necessary)
