### ISSUE TITLE
Fix package on nixpkgs

### ISSUE THREAD

**Issue by qzle** [dustin/mqtt-hs#17]
The package is still broken on nixpkgs due to https://github.com/dustin/mqtt-hs/pull/16.

I have fixed the problem for my personal deployments so this is not urgent, but I would prefer to upstream the change. There are two options:
- You could release a new version which includes the fix
- I could jailbreak the package on nixpkgs (this would make the solver ignore all version bounds)

I'm fine with either option, but if we apply a jailbreak to the package I can't help with future version bumps (I wouldn't notice them).

**Comment by dustin** [comment]
I've release 0.7.1.0.  Sorry for the delay.

**Comment by qzle** [comment]
As I said before, there is no urgency. Thank you for the release and for maintaining the package!
