### ISSUE TITLE
Connect To MQTT with a different Config for URI

### ISSUE THREAD

**Issue by Hydrostatik** [dustin/mqtt-hs#18]
I see the only option in this library is to use the connectURI to actually connect to the MQTT, is it possible to expose a general connect option where we can manually fill in the required information for the connection? Thanks. I am new to Haskell so I can try to implement this in a PR if you think it would be beneficial.

**Comment by dustin** [comment]
I used to have such a thing, but it was awkward to use and didn't do
anything you couldn't do with a uri.  Can you describe your use case a bit
more?

**Comment by Hydrostatik** [comment]
Right, I want to make a utility app for my company. We use a proprietary URI for our MQTT. While I understand that it can be awkward, I think having the flexibility to use the a generic connect (when absolutely necessary) might be useful.

**Comment by dustin** [comment]
Perhaps the easiest thing is to make a utility to convert your proprietary URI to a less proprietary one.  :)

There's just enough setup differences between plain TCP, TLS, and websockets (and secure websockets) that switching based on URI seemed to be the most natural thing to do.  Using the config alone became insufficient when websockets included further path information that seemed like a bad idea to stuff into the configuration.

The most generic mechanism available is `runMQTTConduit` which is the first place that's common across the four supported protocols.  The URI mechanism fans out to four different code paths to handle establishing a connection and having read/write adaptors to feed back into `runMQTTConduit` to do the actual work.  Exposing those adaptors and such would be a lot of noise in the library and limit the ability to improve implementation details.

Is the URI conversion utility function feasible?

**Comment by Hydrostatik** [comment]
Thanks for the pointers! I will take some time to play with what you've suggested.
