### ISSUE TITLE
mqtt-hs for an MQTT server

### ISSUE THREAD

**Issue by cdupont** [dustin/mqtt-hs#19]
Hi,
what would it take to create a haskell MQTT server using mqtt-hs?
i have an REST API server using mongo as a database.
I added some time ago some MQTT endpoints to the server, using mqtt-hs.
It is just filtering MQTT requests, then forwarding them to a Mosquitto backend: https://github.com/Waziup/waziup-api/blob/master/src/MQTT.hs

However, I would like to get rid of the Mosquitto. How complex would that be? I guess I have to implement features such as maintaining a list of subscribers. I don't need the full MQTT specification, just what it takes to make a small REST + MQTT API server, with a mongo backend.
Any chance to have a library "mqtt-broker-hs" sometimes, handling the requests (like Mosquitto)?
Thanks

**Comment by dustin** [comment]
All of my mqtt services are currently using https://github.com/dustin/mqttd which is, as far as I can tell, more feature-complete than mosquitto.  I had a few bugs with mosquitto that were bothering me, so I also wanted to see what it'd take to write such a thing.  :)

I'm not entirely sure how adaptable that is.  Perhaps it'd be possible to extract the state management.  This is an area I'm not super familiar with.  My code currently manages its data structures with STM and persist state with SQLite.  It'd probably be possible to abstract the SQLite bits.

**Comment by cdupont** [comment]
That's great!! I didn't find it last time I looked for an MQTT broker in Haskell. Can it be put on Hackage?

**Comment by dustin** [comment]
I'm not opposed to the idea.  https://hackage.haskell.org/package/mqttd isn't taken.  I think of it more as a program than anything, so it seems a bit odd to me.  It'd be fantastic if someone else could benefit from the service, though.

24 hours of my home mqttd on an Orange Pi looks like this:

<img width="1587" alt="Screen Shot 2021-05-19 at 10 47 41" src="https://user-images.githubusercontent.com/1779/118859957-ac91c300-b88f-11eb-8d93-60e50a584f41.png">

Fairly normal stuff. "actions" is mainly timed tasks for stuff like expiring sessions or retained messages (I use MQTT v5 retention timeouts a lot).  "influx spool" is how much junk [influxer](https://github.com/dustin/influxer) has read and written to disk waiting for connectivity to return so it can stick it in a remote influxdb.

Are you able to try it without hackage and see if it looks remotely useful?  It'd be good to get any obvious stuff fixed up before it publishing it.  I've been relying on it for around a year now and have had fewer problems than I did with mosquitto.  :)

Worth noting that it doesn't have built-in replication.  I don't see that as a useful thing as mosquitto's built-in replication also didn't work well for me, so I wrote [https://github.com/dustin/mqtt-bridge](mqtt-bridge) to handle that.  Specifically, it properly bridges mqtt v5 properties including remaining expiration time on retained items.

**Comment by dustin** [comment]
I'll go ahead and close this since there's a working solution.  Please let me know on https://github.com/dustin/mqttd if there's anything that can make that more useful.

(I've got two open issues that are there for theoretical correctness, but don't affect me)
