### ISSUE TITLE
Export `Filter` and `Topic` constructors 

### ISSUE THREAD

**Issue by riz0id** [dustin/mqtt-hs#28]
Would it be possible to export the constructors for `Topic` and `Filter`? The `mkTopic :: Text -> Maybe Topic` is the only method provided by the API as of now for creating a topic, but there are some cases where I'd like to create a `Topic` without handling the alternative `Nothing` case since I'm certain the `Text` string does not contain any reserved characters.

I believe exporting the `Topic` and `Filter` constructors with a cautionary note and a strong suggestion to use `mkTopic` where possible would be an improvement to the package.

**Comment by dustin** [comment]
You can always use `fromJust . mkTopic` if you're certain it's not invalid.  It will produce a runtime error on invalid input.  The alternative is undefined behavior which I think is less desirable.
