### ISSUE TITLE
0.8.2.3 ?

### ISSUE THREAD

**Issue by kamek-pf** [dustin/mqtt-hs#32]
Hi,

Apparently a version `0.8.2.3` was deployed on Hackage and Stackage a couple days ago, however it appears the last visible commit here happened about 2 months ago. 
The cabal file I see here says `0.8.2.2`.

Is this intentional ? I'm trying to confirm nothing was compromised here.

**Comment by kamek-pf** [comment]
Sounds good, thanks a lot :)

**Comment by kamek-pf** [comment]
Sounds good, thanks :)

**Comment by dustin** [comment]
Yeah, I did some dumb stuff here.  I think I was just trying to get a project building on a newer toolchain and forgot to commit and push stuff.  I think it's all clean now.  Thanks a lot for pointing this out.
