### ISSUE TITLE
How can I set the clientId?

### ISSUE THREAD

**Issue by KeesBleijenberg** [dustin/mqtt-hs#38]
Where can I ask questions about this package?

Maybe the source of my problem is a lack of understanding of mqtt..
The mqtt broker is mosquitto. Some not Haskell processes publish message on the broker. 
Every week I want to log in and get all persistent messages for a topic and  then disconnect. The broker should persist the messages from that week. 
The Haskell client logs in (Qos2 and _cleanSession=false, protocol50, _retainHandling= SendOnSubscribe) and subscrices to the topic.
Every time I log in I get another assigned client identifier and the broker starts a NewSession. That's not what I want. To get old persistent messages the clientId should stay the same?
Where can I set the clientId?
I wonder whether I have to subscribe after the first time. The broker should know what to send, without subscribing by the client, or...?

Thanks,
Kees

**Comment by dustin** [comment]
You can connect with `mqtt://hostname/#clientID`.

Or in v5, the broker will return the generated client ID and you can re-use it.  The `mqtt-watch` command source does this.  You can [see how it updates](https://github.com/dustin/mqtt-hs/blob/master/app/mqtt-watch/Main.hs#L105) the URI (which it keeps in an `IORef`).  

By default, the above [won't send subscriptions](https://github.com/dustin/mqtt-hs/blob/master/app/mqtt-watch/Main.hs#L94-L96) again if it's resuming, but you can tell it to if you want.

**Comment by KeesBleijenberg** [comment]
I see. I missed the #clientId. Your program works with the mosquitto broker without problems.
If I want to resume the program I have to save the clientId in a file and at startup use the stored clientId in the URI.

Thanks,
Kees
