### ISSUE TITLE
Add to Stackage?

### ISSUE THREAD

**Issue by ocramz** [dustin/mqtt-hs#4]
Hi, it would be great if you could add this library to Stackage so that we can all keep an eye on its stability.
If you are too busy to maintain it I offer myself as co-maintainer.

**Comment by dustin** [comment]
Hey.  If you're still up to it, it'd be great to have someone else paying a bit of attention since I've clearly missed out on a few things here.  I just released 0.5.0.0 (and then applied a couple bug fixes).  I think overall the release is pretty good.  It should be good for mass consumption.

**Comment by cdupont** [comment]
+1 Stackage woudl be great!

**Comment by kamek-pf** [comment]
Same here, if you have a few minutes to lose, the procedure is explained there:
https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by dustin** [comment]
Thanks for the pointer.  I've sent https://github.com/commercialhaskell/stackage/pull/6025
